import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header/Header'
import Nav from '../components/Nav/Nav'
import Results from '../components/Results/Results'
import requests from '../utils/requests'

export default function Home( {results} ) {
  // console.log(results)
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* <div>
        <h1>Hulu 2.0</h1>
      </div> */}

      {/* Header */}
      <Header />

      {/* NavBar */}
      <Nav/>

      {/* Results */}
      <Results results={results} />
    </div>
  )
}

export async function getServerSideProps(context) {
  // console.log(context)
  const genre = context.query.genre;

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
                              ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
